### PR TITLE
Add some missing special characters to the link regex

### PR DESCRIPTION
**Pull request by alex-mechler**
cc @rafecolton 

### Fixed Issues
Needed to fix https://github.com/Expensify/Expensify/issues/153365

# Tests
1. Automated tests updated

# QA
Will be qa'd in the Expensify.cash pr

### CODE REVIEW

**Review by roryabraham — APPROVED** [review]
LGTM 👍

**Comment by roryabraham** [comment]
@alex-mechler are you going to deploy this? https://stackoverflow.com/c/expensify/questions/7216

**Comment by alex-mechler** [comment]
Hmm, I'm a bit confused about that process. Looking in the repos it seems we are still using hashes, and no one has deployed to that in 3 months. Is the current process to deploy? Did I miss a process change email sometime?

**Comment by roryabraham** [comment]
Oh, looks like you're right and we're just using hashes for now. My mistake – I was just going off of what's in the README for this repo.

**Comment by marcaaron** [comment]
Yep read me needs to be updated.

**Comment by alex-mechler** [comment]
So making sure I understand, the readme needs to change back to the hash changing method? I'll get that done

**Pull request merged**
