### PR TITLE
fix email rendering bug

### PR DESCRIPTION
**Pull request by nicodev-git**
TAG_REVIEWER will you please review this?

This PR fixed email link rendering bug by adding additional email regular expressions to the current rules.

### Fixed Issues
https://github.com/Expensify/Expensify.cash/issues/990

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

### CODE REVIEW

**Comment by nicodev-git** [comment]
@roryabraham  sorry, I created a new PR again.

**Review by roryabraham — APPROVED** [review]
LGTM

**Comment by roryabraham** [comment]
It worked 🎉

**Comment by roryabraham** [comment]
Thanks for working through that. I made an update to `CONTRIBUTING.md` to provide clearer instructions and hopefully prevent this from happening again.

**Pull request merged**
