### PR TITLE
Skip match if there is space after Starting or before ending main symbol in Expensimark [ ~ , _ ,* ] only

### PR DESCRIPTION
**Pull request by parasharrajat**
@thienlnam will you please review this?

[Explanation of the change or anything fishy that is going on]

### Fixed Issues
$ https://github.com/Expensify/Expensify.cash/issues/2846

# Tests
1. What unit/integration tests cover your change? What auto QA tests cover your change?
I have extended the existing tests to cover the Changes.
1. What tests did you perform that validates your changes worked?
Jest test & manual inspection.

# QA
1. What does QA need to do to validate your changes?
 a. Try to parse a message which contains any of the Italic, Strikethrough, bold text.
 b. Only text containing no space after starting or before ending symbol will be parsed and converted to html.
 
1. What areas do they need to test for regressions?
1. Test messages on the E.cash app. If they are rendered as expected or not.

### CODE REVIEW

**Review by thienlnam — APPROVED** [review]
Nice 👍

**Comment by thienlnam** [comment]
Looks like not all the commits have been signed though

**Comment by parasharrajat** [comment]
Sorry actually none of them are. Let me sign them. Hold up.

**Comment by parasharrajat** [comment]
@thienlnam Sorry for the force push but I have signed them off. Also, if this looks good. Please merge it. Thanks.

**Review by thienlnam — APPROVED** [review]

**Pull request merged**
