### PR TITLE
Issue 26490 remove replacebr

### PR DESCRIPTION
**Pull request by nikosamofa**
This PR:
- removes the `replacebr` rule option inside `ExpensiMark.rules`

### Fixed Issues
$ https://github.com/Expensify/App/issues/26490
$ https://github.com/Expensify/App/issues/16982

# Tests
Unit testing
1. Updated existing tests which are affected by this change to pass
2. Added new unit testing

Testing in the `expensify-app`
1. On your local dev environment of `expensify-app`, open `node_modules/expensify-common/lib/ExpensiMark.js` file
2. Remove `replacebr` rule
3. Run the app and test with the following recordings

Test Strings
````
```
code1
```
text
```
code2
```
````
````
|
```
code
```
````
````
```
code

```
````
````
message1```code```message2
````
````
message1 ``` code ``` message2
````
````
message1
```code```
message2
````
````
message1
``` code ```
message2
````
````
message1
```

code
```
message2
````
````
message1
```

code

```
message2
````
````
message1
```


code

```
message2
````
````
message1
```

code


```
message2
````

https://github.com/Expensify/expensify-common/assets/30532000/05da9434-565c-41d5-8ddf-a5f5cd9f9727

https://github.com/Expensify/expensify-common/assets/30532000/4fd9da4a-8995-4c49-9282-f6c131a3ad91

https://github.com/Expensify/expensify-common/assets/30532000/671a105d-2af7-4f8d-9f1f-40218b50cd5b

https://github.com/Expensify/expensify-common/assets/30532000/941a2d8c-40ce-42c6-82bb-203c0f15c846

https://github.com/Expensify/expensify-common/assets/30532000/d9b475ee-0f8e-4c3a-abd7-454108805e3e

# QA
Same as test

### CODE REVIEW

**Comment by nikosamofa** [comment]
> Please add test strings in Tests step for easier test. Example: #573.

Thanks, addressed by https://github.com/Expensify/expensify-common/pull/606/commits/7992a004cd3abaddb74f4444c409e9675956cb79

**Comment by nikosamofa** [comment]
@0xmiroslav Do I need to add those cases to the unit testing or to the test strings in the PR description?

**Comment by danieldoglas** [comment]
@0xmiroslav can you please do the review checklist on this one?

Thanks!

**Comment by nikosamofa** [comment]
@0xmiroslav After this PR is merged, do I need to create another PR in the App to update the expensify-common package version? What will be measured as the days for the PR merged - this PR or another PR for App?
Upwork contract says that if I can get merged within 3 days, I can get 50% bonus, but if merged after 9 days, I will get penalty

**Comment by nikosamofa** [comment]
@0xmiroslav Yes, we can see the same result in the current staging environment.
I assume if we want to fix it, we will need to create another issue and address it, but as we don't really want the edit mode to be exactly as the original text, it can be decided by the product team.

**Review by danieldoglas — APPROVED** [review]

**Comment by nikosamofa** [comment]
@danieldoglas Is there anything I need to do to merge this PR?

**Comment by nikosamofa** [comment]
@danieldoglas Can you please update the version of `expensify-common`?

**Pull request merged**
