### PR TITLE
Edited autoEmail regex

### PR DESCRIPTION
**Pull request by s77rt**
### Fixed Issues
https://github.com/Expensify/App/issues/13073

# Tests
The email should always be `test@gmail.com` except for 4th case it should be `_test@gmail.com`
```
test@gmail.com
*test@gmail.com*
_test@gmail.com_
*_test@gmail.com*
~_test@gmail.com_~
*_test@gmail.com_*
*_*_test@gmail.com_*_*
*__test@gmail.com__*
*__*test@gmail.com*__*
_~__test@gmail.com__~_
**__test@gmail.com__**
```

# QA
1. Login to any Expensify account
2. Go to any chat
3. Send `test@gmail.com`
4. Verify that the email is sent correctly
5. Send `*test@gmail.com*`
6. Verify that the email is sent correctly in bold format
7. Send `_test@gmail.com_`
8. Verify that the email is sent correctly in italic format
9. Send `*_test@gmail.com_*`
10. Verify that the email is sent correctly in bold and italic format

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/16493223/205886380-ababe16a-9d93-4630-b1d8-40b7778b6501.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/16493223/205886773-71ac1fb7-6a45-436f-9c67-802c5d012e8b.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/16493223/205887556-4acc9f0a-1f0b-4135-bafe-29c71dd64c27.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/16493223/205887953-14465d52-3c37-476f-aa9e-80e379e8aa9f.mp4

</details>

<details>
<summary>iOS</summary>

This video has been compressed, it may not work on browsers, download it first and use a video player.

https://user-images.githubusercontent.com/16493223/205889210-0cb41521-6e5d-42f7-aa34-ec5da4015ed9.mp4

</details>

<details>
<summary>Android</summary>

This video has been compressed, it may not work on browsers, download it first and use a video player.

https://user-images.githubusercontent.com/16493223/205889556-6988514e-3cfd-4fe8-8428-4fcde7062559.mp4

</details>

### CODE REVIEW

**Comment by s77rt** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thesahindia** [comment]
@s77rt, please add the screenshots for all platforms.

**Comment by s77rt** [comment]
@thesahindia Updated

**Comment by cristipaval** [comment]
Hey @s77rt ! Thanks for the PR. I just updated the **Fixed issues** section [here](https://github.com/Expensify/expensify-common/pull/479#issue-1477208527) to mark the issue as partially fixed (by removing the `$` in front of the issue link). It will be completely fixed when the new `expensify-common` version will be added to the App.

I'll test your PR asap. In the meantime, could you please fix the failed checks?

**Comment by s77rt** [comment]
@cristipaval FIxed please accept to run the checks again...

**Review by cristipaval — CHANGES_REQUESTED** [review]
Thank you so much @s77rt ! 
Please have a look at the screen recording below. It looks like edit action does not work as expected.

https://user-images.githubusercontent.com/18078393/205905945-88499202-df76-4e14-9d3a-07c970d0d433.mov

**Comment by thesahindia** [comment]
These 3 cases are failing -
```
*_*_test@gmail.com_*_*
_~__test@gmail.com__~_
*__*test@gmail.com*__*
```

**Comment by s77rt** [comment]
I think I found the root cause: `*_*_*`
1. We do apply italic rule first, so this will become: `*<em>*</em>*`
2. Then we apply bold rule: `<strong><em></strong></em>*`

The results is an invalid html and therefor we get a different value on the edit mode as `htmlToMarkdownRules` does not know how to handle such an invalid html

**Comment by s77rt** [comment]
This issue seems to exists before this PR. Should we fix it? It may be fixed by checking if the surrounded text is a valid html, if it's do nothing, if not escape the text.

What do you think? to be fixed or this is an edge case and can be ignored?

**Comment by s77rt** [comment]
cc @thesahindia @cristipaval ^

**Comment by s77rt** [comment]
Setting this back to open and ready for review since I don't think we have to cover the failing cases on edit as explained above.

**Comment by thesahindia** [comment]
> This issue seems to exists before this PR. Should we fix it? It may be fixed by checking if the surrounded text is a valid html, if it's do nothing, if not escape the text.

That makes sense to me. We should open a new issue for it. Given that it's an edge case maybe we can leave it as it is.

**Comment by thesahindia** [comment]
## Reviewer Checklist

- [x] I have verified the author checklist is complete (all boxes are checked off).
- [x] I verified the correct issue is linked in the `### Fixed Issues` section above
- [x] I verified testing steps are clear and they cover the changes made in this PR
    - [x] I verified the steps for local testing are in the `Tests` section
    - [x] I verified the steps for Staging and/or Production testing are in the `QA steps` section
    - [x] I verified the steps cover any possible failure scenarios (i.e. verify an input displays the correct error message if the entered data is not correct)
    - [x] I turned off my network connection and tested it while offline to ensure it matches the expected behavior (i.e. verify the default avatar icon is displayed if app is offline)
- [x] I checked that screenshots or videos are included for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I included screenshots or videos for tests on [all platforms](https://github.com/Expensify/App/blob/main/contributingGuides/CONTRIBUTING.md#make-sure-you-can-test-on-all-platforms)
- [x] I verified tests pass on **all platforms** & I tested again on:
    - [x] iOS / native
    - [x] Android / native
    - [x] iOS / Safari
    - [x] Android / Chrome
    - [x] MacOS / Chrome
    - [x] MacOS / Desktop
- [x] If there are any errors in the console that are unrelated to this PR, I either fixed them (preferred) or linked to where I reported them in Slack
- [x] I verified proper code patterns were followed (see [Reviewing the code](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md#reviewing-the-code))
    - [x] I verified that any callback methods that were added or modified are named for what the method does and never what callback they handle (i.e. `toggleReport` and not `onIconClick`).
    - [x] I verified that comments were added to code that is not self explanatory
    - [x] I verified that any new or modified comments were clear, correct English, and explained "why" the code was doing something instead of only explaining "what" the code was doing.
    - [x] I verified any copy / text shown in the product was added in all `src/languages/*` files
    - [x] I verified any copy / text that was added to the app is correct English and approved by marketing by adding the `Waiting for Copy` label for a copy review on the original GH to get the correct copy.
    - [x] I verified proper file naming conventions were followed for any new files or renamed files. All non-platform specific files are named after what they export and are not named "index.js". All platform-specific files are named for the platform the code supports as outlined in the README.
    - [x] I verified the JSDocs style guidelines (in [`STYLE.md`](https://github.com/Expensify/App/blob/main/contributingGuides/STYLE.md#jsdocs)) were followed
- [x] If a new code pattern is added I verified it was agreed to be used by multiple Expensify engineers
- [x] I verified that this PR follows the guidelines as stated in the [Review Guidelines](https://github.com/Expensify/App/blob/main/contributingGuides/PR_REVIEW_GUIDELINES.md)
- [x] I verified other components that can be impacted by these changes have been tested, and I retested again (i.e. if the PR modifies a shared library or component like `Avatar`, I verified the components using `Avatar` have been tested & I retested again)
- [x] I verified all code is DRY (the PR doesn't include any logic written more than once, with the exception of tests)
- [x] I verified any variables that can be defined as constants (ie. in CONST.js or at the top of the file that uses the constant) are defined as such
- [x] If a new component is created I verified that:
    - [x] A similar component doesn't exist in the codebase
    - [x] All props are defined accurately and each prop has a `/** comment above it */`
    - [x] The file is named correctly
    - [x] The component has a clear name that is non-ambiguous and the purpose of the component can be inferred from the name alone
    - [x] The only data being stored in the state is data necessary for rendering and nothing else
    - [x] For Class Components, any internal methods passed to components event handlers are bound to `this` properly so there are no scoping issues (i.e. for `onClick={this.submit}` the method `this.submit` should be bound to `this` in the constructor)
    - [x] Any internal methods bound to `this` are necessary to be bound (i.e. avoid `this.submit = this.submit.bind(this);` if `this.submit` is never passed to a component event handler like `onClick`)
    - [x] All JSX used for rendering exists in the render method
    - [x] The component has the minimum amount of code necessary for its purpose, and it is broken down into smaller components in order to separate concerns and functions
- [x] If a new CSS style is added I verified that:
    - [x] A similar style doesn't already exist
    - [x] The style can't be created with an existing [StyleUtils](https://github.com/Expensify/App/blob/main/src/styles/StyleUtils.js) function (i.e. `StyleUtils.getBackgroundAndBorderStyle(themeColors.componentBG`)
- [x] If the PR modifies a generic component, I tested and verified that those changes do not break usages of that component in the rest of the App (i.e. if a shared library or component like `Avatar` is modified, I verified that `Avatar` is working as expected in all cases)
- [x] If the PR modifies a component related to any of the existing Storybook stories, I tested and verified all stories for that component are still working as expected.
- [x] I have checked off every checkbox in the PR reviewer checklist, including those that don't apply to this PR.

### Screenshots/Videos
<details>
<summary>Web</summary>
Screenshot 2022-12-07 at 3 36 53 PM






</details>

<details>
<summary>Mobile Web - Chrome</summary>
Screenshot 2022-12-07 at 3 45 58 PM





</details>

<details>
<summary>Mobile Web - Safari</summary>
Screenshot 2022-12-07 at 3 34 36 PM





</details>

<details>
<summary>Desktop</summary>
Screenshot 2022-12-07 at 3 46 51 PM






</details>

<details>
<summary>iOS</summary>
Screenshot 2022-12-07 at 3 38 05 PM






</details>

<details>
<summary>Android</summary>



Screenshot 2022-12-07 at 3 44 03 PM



</details>

**Review by thesahindia — APPROVED** [review]
Works well for me! Some edge cases are failing but they aren't specific to this PR so approving.

cc: @thienlnam

**Review by cristipaval — APPROVED** [review]
> This issue seems to exists before this PR. Should we fix it? It may be fixed by checking if the surrounded text is a valid html, if it's do nothing, if not escape the text.

Thanks for checking! Yeah, if the issue existed before it's fair to create a separate issue.

**Comment by thesahindia** [comment]
@cristipaval, by looking at the previous PRs I think the version needs to be updated by Expensify engineers.

**Comment by cristipaval** [comment]
Done ✅  --> https://github.com/Expensify/App/pull/13394

**Pull request merged**
