### PR TITLE
Fix: multi level blockquote HTML to Markdown

### PR DESCRIPTION
**Pull request by dragnoir**
This PR fixes the issue of inconsistency in Block Quote Usage Between the saved HTML and how it's rendered into markdown.

https://github.com/Expensify/expensify-common/assets/12425932/4c3afc10-ba13-4f38-8eb6-58801b52e6e3

### Fixed Issues
$ GH_LINK https://github.com/Expensify/App/issues/40571

# Tests
Unit tests added in the PR

# QA

1. bump expensify-common version in E/App
2. On Workspace description, use ">>> ABC"
3. save the new description and edit it again
4. verify that the displayed value to edit is the same ">>> ABC" and not "> ABC"

### CODE REVIEW

**Review by MonilBhavsar — COMMENTED** [review]
lint errors to fix

**Comment by jjcoffee** [comment]
@dragnoir Could you add some test steps?

**Comment by jjcoffee** [comment]
@dragnoir Is [your comment](https://github.com/Expensify/expensify-common/pull/693#issuecomment-2120265060) related to the failing test?

**Comment by jjcoffee** [comment]
> I am working on some test steps and checking the failing test.

@dragnoir Thank you! I've made some initial tests and it seems to be working nicely, so that's good. Could you give us a rough ETA so we can keep things moving?

**Comment by jjcoffee** [comment]
> I think the tests are now passed well. Can you pls check from your side?

Yup tests are passing now!

**Review by jjcoffee — APPROVED** [review]
LGTM and tests well. I think we can run the full set of platform tests on the App PR.


https://github.com/Expensify/expensify-common/assets/27287420/a1e408e0-d13a-4a9b-adf1-037c47df6bd4

**Comment by jjcoffee** [comment]
All yours @MonilBhavsar :pray:

**Comment by jjcoffee** [comment]
Actually for completeness can you add test steps here @dragnoir?

**Comment by MonilBhavsar** [comment]
@dragnoir bump on above comment

**Review by MonilBhavsar — APPROVED** [review]
Thanks!

**Comment by MonilBhavsar** [comment]
Please open a PR in App repo with referencing the merge commit - 6cfc572191751c7440ce5c9364c89674dcca8841

**Comment by MonilBhavsar** [comment]
I think you can use `npm install` as mentioned here https://github.com/Expensify/expensify-common?tab=readme-ov-file#installation

**Comment by MonilBhavsar** [comment]
https://github.com/Expensify/expensify-common?tab=readme-ov-file#deploying-a-change-expensify-only
May be you can try running `npm install expensify-common@2.0.5`
and push package.json and package.lock.json files

**Pull request merged**
