### PR TITLE
Fixed characters support between [] for Hyperlinks

### PR DESCRIPTION
**Pull request by mananjadhav**
@stitesExpensify will you please review this updated PR?

- Updated the regex for handling characters between [] for the hyperlink.

### Fixed Issues
$ Fixes: [Expensify/App#4229](https://github.com/Expensify/App/issues/4229)

# Tests
1. "Test markdown and URL links with inconsistent starting and closing parens" covers testing of the given changes
1. Tested against incorrect pairs, symbols, and special characters handling

# QA
1. Test with different string patterns for the URLs  
2. Explore complex strings to validate the regex
2. Regression has to be run for inconsistent parenthesis and links with style

### CODE REVIEW

**Review by stitesExpensify — APPROVED** [review]

**Comment by stitesExpensify** [comment]
As mentioned [here](https://github.com/Expensify/expensify-common/pull/400#issuecomment-887871454) we should have Applause do extra QA to make sure the new pattern does not break things.

**Comment by parasharrajat** [comment]
So one behaviour change from the changes here
1. [ link `test`](google.com) will become  => link `test` which was not the case earlier. 

cc: @stitesExpensify

**Comment by mananjadhav** [comment]
@parasharrajat  Is that different from what is expected?

**Comment by parasharrajat** [comment]
I think it's fine as Github supports it.

**Comment by stitesExpensify** [comment]
is "link" in "link `test`" still a hyperlink?

**Comment by parasharrajat** [comment]
Yes

**Comment by stitesExpensify** [comment]
Cool, I think that's fine then. Thanks for the heads up though!

**Pull request merged**
