### PR TITLE
fix issue #1476 on Expensify.cash repo

### PR DESCRIPTION
**Pull request by minbaghdasaryan**
@Gonals will you please review this?

[Explanation of the change or anything fishy that is going on]

### Fixed Issues
$ Expensify/Expensify.cash#1476

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
I have changed `ExpensiMark` file only, so unit tests on this file cover this change.

1. What tests did you perform that validates your changed worked?
I have run tests on the `expensify-common` project and all the tests suits was successfully passed.

# QA
1. What does QA need to do to validate your changes?
QA can validate my PR by updating `expensify-common` library and sending the test message on the relative issue.

1. What areas to they need to test for regressions?

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Review by deetergp — CHANGES_REQUESTED** [review]
Change looks good, but let's add a test for this change.

**Comment by minbaghdasaryan** [comment]
Thanks @deetergp 
I will add it.

**Comment by laurenreidexpensify** [comment]
@minbaghdasaryan have you had a chance to implement changes? Thanks

**Comment by minbaghdasaryan** [comment]
I am working on it now and can update within 2 hours

**Pull request closed without merging**
