### PR TITLE
Fix combobox click non existing value

### PR DESCRIPTION
**Pull request by aldo-expensify**
Clicking an option that doesn't exist when  `allowAnyValue = true` doesn't stick.

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/215741

# Tests

1. Checkout this PR: https://github.com/Expensify/Web-Expensify/pull/34070
1. Go to expenses page
2. Type an option that doesn't exist in the Tag filter
3. Click the option appearing with the text you typed
4. Check that the dropdown closes and the input still has the text you typed
2. Type another option that doesn't exist in the Tag filter
3. Press Enter key
5. Check that the dropdown closes and the input still has the text you typed

### CODE REVIEW

**Comment by aldo-expensify** [comment]
The failing tests is already failing in `main` branch:
Screen Shot 2022-06-21 at 4 39 27 PM

**Comment by aldo-expensify** [comment]
Update with main, test not failing any more. Ready for review.

**Review by Luke9389 — CHANGES_REQUESTED** [review]
Just a tiny NAB

**Comment by aldo-expensify** [comment]
Thanks @Luke9389 , committed your suggestion

**Review by Luke9389 — APPROVED** [review]
👍

**Pull request merged**
