### PR TITLE
update htmlToMarkdownRules userMention and reportMention

### PR DESCRIPTION
**Pull request by ahmedGaber93**
CC @marcaaron @lakchote @eh2077 

When We copy `<mention-user accountID="1234" />` as `text/html` to clipboard on the web [here](https://github.com/Expensify/App/blob/571a79d3d43f68ace68406a2e4bcb17604289103/src/libs/Clipboard/index.ts#L119-L123). The paste value [here](https://github.com/Expensify/App/blob/d0513b9513a091cb49f79fbc429b73d2a987cfce/src/hooks/useHtmlPaste/index.ts#L109) paste with different format `<meta charset='utf-8'><html><head></head><body><mention-user accountid="1234"></mention-user></body></html>`

(`<openTag></closeTag>` not `<closedTag />`), and this format not match rule `reportMention` in `ExpensiMark`

This issue will update htmlToMarkdownRules `userMention` and `reportMention` regex to work for both self closing and non self closing tags.

### Fixed Issues
$ https://github.com/Expensify/App/issues/40477
$ https://github.com/Expensify/App/issues/40403

# Tests
1. pull this branch
2. run `npm install & npm run build`
3. copy `dist` folder to E/App to `node_modules/expensify-common/dist`
4. run E/App and open any report
5. mention a user in message and send it
6. right click > copy to clipboard and paste it in a composer and Verify that message is pasted correctly
7. mention a report in message and send it
8. right click > copy to clipboard and paste it in a composer and Verify that message is pasted correctly

### Screenshots/Videos
<details>
<summary>Android: Native</summary>

https://github.com/Expensify/expensify-common/assets/41129870/1b5d617e-a637-4e2b-81e1-f241a2b49bc1

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/Expensify/expensify-common/assets/41129870/727e45f3-502e-4b24-8822-abed72c76bd4

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/Expensify/expensify-common/assets/41129870/d2be1322-e597-4049-b72c-d1a8df474e65

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/Expensify/expensify-common/assets/41129870/b58a0e9c-c6fd-44af-b7dd-b1f171790cf8

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/Expensify/expensify-common/assets/41129870/8c68d435-11f7-4afe-854c-37434a400d62

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/Expensify/expensify-common/assets/41129870/5025f48e-fc4d-414c-996e-71a8367940f1

</details>

### CODE REVIEW

**Comment by ahmedGaber93** [comment]
### Bug
add some text after the mention or more than one mention not pasted correctly.

<details>
<summary>video</summary>

https://github.com/Expensify/expensify-common/assets/41129870/0cc72730-525f-4c83-9277-9478c254ddee

</details>

it seems browser `clipboard` not parse self-clothing tags with type `text/html` correctly and ignore it

We write to clipboard [here](https://github.com/Expensify/App/blob/571a79d3d43f68ace68406a2e4bcb17604289103/src/libs/Clipboard/index.ts#L119-L123). And get clipboard data [here](https://github.com/Expensify/App/blob/d0513b9513a091cb49f79fbc429b73d2a987cfce/src/hooks/useHtmlPaste/index.ts#L109) 
```javascript
// coping value as text/html
<mention-report reportID="1234" /> text after
// paste value as text/html
<mention-report reportID="1234"> text after</mention-report>

// coping value as text/html
<mention-report reportID="1234" /> <mention-user accountID="1234" />
// paste value as text/html
<mention-report reportID="1234"> <mention-user accountID="1234"></mention-user></mention-report>
```

### Solution
convert self-clothing closing tags to non self-clothing before writing it to clipboard [here](https://github.com/Expensify/App/blob/571a79d3d43f68ace68406a2e4bcb17604289103/src/libs/Clipboard/index.ts#L119-L123).
```javascript
const htmlNonClosingTags = html.replace(/<mention-report reportID="(\d+)" *\/>/gi, '<mention-report reportID="$1"></mention-report>')
    .replace(/<mention-user accountID="(\d+)" *\/>/gi, '<mention-user accountID="$1"></mention-user>')
```

**Comment by eh2077** [comment]
@ahmedGaber93 I'd like to confirm one thing - in report action, we only save self-closing tags, like `<mention-report reportID="1234" />` and  `<mention-report reportID="1234" /> <mention-user accountID="1234" />`, right?

**Comment by ahmedGaber93** [comment]
@eh2077 I think we use combine of them. In optimistic data, we use `<mention-report>#report</mention-report>` and in backend data it converted to based ID `<mention-report reportID="1234" />`

**Comment by eh2077** [comment]
So we'll also need to fix in App codebase to convert self-closing tags to paired tags when setting clipboard right?

**Comment by ahmedGaber93** [comment]
Yes, we need that to cover this case https://github.com/Expensify/expensify-common/pull/741#issuecomment-2209458519

**Review by marcaaron — DISMISSED** [review]

**Comment by marcaaron** [comment]
@ahmedGaber93 I can't merge this because you have unverified commits. Please resolve that and tag me again when it's ready.

**Comment by ahmedGaber93** [comment]
@marcaaron commits now are verified.

**Comment by ahmedGaber93** [comment]
@marcaaron hope you noticed this comment, I will create a PR in E/App also to fix this.

**Comment by marcaaron** [comment]
All of them need to be verified. Can you squash the initial commit?

**Comment by ahmedGaber93** [comment]
I don't use squash before, what about force push?

**Review by marcaaron — APPROVED** [review]
Perfect, thanks!

**Pull request merged**
