### PR TITLE
Handle cases without currency symbols

### PR DESCRIPTION
**Pull request by Li357**
### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/309211
$ https://github.com/Expensify/Expensify/issues/309227

# Tests
Added two unit tests to test cases without currency symbols and without passing a currency string at all.

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

Run the QA steps in the linked issues and verify that the error does not occur.

### CODE REVIEW

**Comment by techievivek** [comment]
@Li357 QQ: Did you confirm if those 2 issues are no longer reproducible?

**Comment by Li357** [comment]
Just confirmed https://github.com/Expensify/Expensify/issues/309211 is no longer producible

**Comment by Li357** [comment]
@techievivek Verified both are not reproducible!

**Comment by techievivek** [comment]
I confirmed the other one is not reproducible with this change.

**Review by techievivek — APPROVED** [review]
Looks good. Thanks for the quick fix.

**Comment by techievivek** [comment]
@Li357 Let's bump the new version in Web-E and I can CP that to staging.

**Pull request merged**
