### PR TITLE
Enable display of empty blockquotes

### PR DESCRIPTION
**Pull request by BrtqKr**
First part of the blockquotes display-related prs. 

image

image

image

### Fixed Issues
$ https://github.com/Expensify/App/issues/43199 
$ https://github.com/Expensify/App/issues/42082
$ https://github.com/Expensify/App/issues/43323

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
A lot of tests had to be adjusted because of the changes to the logic (only treating "&gt; " as a blockquotes and allowing blank lines in other cases)

/__tests__/ExpensiMark-HTML-test.js
updated:
- `Test quotes markdown replacement with quotes ends with blank quote rows`
- `Test quotes markdown replacement with quotes includes a middle blank quote row`
- `Test quotes markdown replacement with quotes includes multiple middle blank quote rows`
- `Test quotes markdown replacement with text includes blank quotes`
- `Test quotes markdown replacement with heading inside`
- `Test markdown quotes without spaces after > should not be parsed`
- `Test quotes markdown replacement with text includes multiple spaces`
- `test max level of blockquote (3)`

added:
- `Test quotes markdown with blank last line`
- `Test quotes markdown with last entry lacking space`

1. What tests did you perform that validates your changed worked?

- copy the code for ExpensiMark and replace it in the NewDot node modules 
- send a message presented below

```
> > > test
> > test2
> 
```

- verify that the empty blockquote in the last row is being displayed correctly

# QA
1. What does QA need to do to validate your changes?
Steps described in tests sections

1. What areas to they need to test for regressions?
Everything related to the empty blockquotes, but most importantly:

- mixing blockquotes with standard messages
- nesting blockquotes

### CODE REVIEW

**Review by BartoszGrajdek — APPROVED** [review]

**Review by arosiclair — DISMISSED** [review]
Seems okay but I'm not really familiar. Adding @thienlnam to this as well

**Review by thienlnam — CHANGES_REQUESTED** [review]
What's up with the changes in ExpensiMark-HTML-test? Are these just linter additions? Additionally, might have missed this but I don't see any added tests in that file as well for these new changes. Could we please add those (or maybe just link to them in case I missed it)

**Comment by BrtqKr** [comment]
@thienlnam

- those were mostly the adjustments to the tests since this PR changes the way blockquotes are being treated, but I've added some directly related tests for some of the cases
- Also, there have been two tickets with the issues I've referenced - one of them had been solved with the changes present when I marked this PR as ready, but the second one still required some changes to handle the blockquote if it was the last entry in the processed text.

**Review by thienlnam — APPROVED** [review]
Great, thank you!

**Pull request merged**
