### PR TITLE
Validate phone numbers in different formats

### PR DESCRIPTION
**Pull request by tienifr**
Current `isValidPhone` function only validates E.164 standard phone numbers but not others causing misunderstandings and worng usages. This PR:
1. Mark `isValidPhone` as deprecated
2. Replace `isValidPhone` with `isValidE164Phone`
3. Add a new `isValidPhoneFormat` to validate phone numbers in different formats

```
significant: 4404589784
international: +1 440-458-9784
e164: +14404589784
national: (440) 458-9784
123.456.7890
```

### Fixed Issues
$ https://github.com/Expensify/App/issues/37723

# Tests
**1. What unit/integration tests cover your change? What autoQA tests cover your change?**

This is a renaming refactor so no need to add new unit tests.

**2. What tests did you perform that validates your changed worked?**

- Test in Expensify App follow these steps:

1. Go to Workspace > Bank account.
4. Initiate the add BA flow
5. Proceed to Company's phone number step
6. Enter a random US number in national format `(xxx) xxx-xxxx`, e.g., "(440) 458-9784"
7. Press Next
8. Verify that the phone number is parsed successfully

# QA

**1. What does QA need to do to validate your changes?**

Test in Expensify App follow these steps:

1. Go to Workspace > Bank account.
2. Initiate the add BA flow
3. Proceed to Company's phone number step
4. Enter a random US number in national format `(xxx) xxx-xxxx`, e.g., "(440) 458-9784"
5. Press Next
6. Verify that the phone number is parsed successfully

**2. What areas to they need to test for regressions?**

NA

# Screenshots

https://github.com/Expensify/expensify-common/assets/113963320/51e85355-96ae-43b4-a010-bbf2be1a7c18

### CODE REVIEW

**Comment by Pujan92** [comment]
@tienifr aren't we supposed to add `isValidPhone` [logic](https://github.com/Expensify/App/pull/38993/files#diff-decc75ea700d62d9f4a8d3d874bff836f8066c95971c1e13dac23ee4b6c14225R290) here in common?

**Comment by Pujan92** [comment]
> @tienifr aren't we supposed to add `isValidPhone` [logic](https://github.com/Expensify/App/pull/38993/files#diff-decc75ea700d62d9f4a8d3d874bff836f8066c95971c1e13dac23ee4b6c14225R290) here in common?

@grgia Do you think `isValidPhone` needs to be added in common which can be used by other projects or let it be in E/App only?

**Comment by Pujan92** [comment]
> @Pujan92 Yes, I just added it.

Thanks!

**Comment by rlinoz** [comment]
This looks good, but may silently break OldDot, so I am waiting a little to review and merge

**Comment by Pujan92** [comment]
@tienifr Looks good to me, better if you add some tests here for `isValidPhone` and `isValidE164Phone`
https://github.com/Expensify/expensify-common/blob/1247a822328011083a13abc769ba1911c3586338/__tests__/Str-test.js#L110-L111

**Comment by rlinoz** [comment]
So, I was thinking about this, and how we can merge this without breaking other parts of the application that depend on it.

What if we:
1. Deprecate the `isValidPhone` and keep its behavior
2. Keep the new `isValidE164Phone` and mention it in the deprecated message of the `isValidPhone`
3. Create a new `isValidPhoneFormat` or something like that, and make it have the behavior of the new `isValidPhone`, also link this in the deprecated method so people know what method to look for depending on what they want

cc: @Pujan92 @tienifr @grgia

**Comment by Pujan92** [comment]
@rlinoz As @tienifr said we have covered all occurrences in the App and going to update it in the App [PR](https://github.com/Expensify/App/pull/38993), @grgia My only concern is to confirm and check whether any other repo is using this function or not. If it is used then with the version bump we also need to rename those occurrences.

Screenshot 2024-03-29 at 17 27 47

**Comment by rlinoz** [comment]
This is used in Web-Expensify and Web-Secure.

My point is, if we merge this and someone updates the expensify-common lib in one of the repos before we merge the renaming, we will break this validation.

**Comment by Pujan92** [comment]
Ah, ok @rlinoz . If that is the case then for the safer side, we can follow the approach that you mentioned [here](https://github.com/Expensify/expensify-common/pull/672#issuecomment-2026017330). With that, we may need 2nd PR for removing `isValidPhone` later once we update the occurrences in all repo to use the new function name.

**Comment by Pujan92** [comment]
Thanks @tienifr, Looks fine to me. cc: @rlinoz @grgia

**Review by rlinoz — APPROVED** [review]
Thanks!

**Review by grgia — APPROVED** [review]

**Pull request merged**
