### PR TITLE
Add email link rule

### PR DESCRIPTION
**Pull request by nicodev-git**
TAG_REVIEWER will you please review this?

This PR fixed email link rendering bug by adding additional email regular expressions to the current rules.

### Fixed Issues
https://github.com/Expensify/Expensify.cash/issues/990

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
Jest test convers my changes
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

### CODE REVIEW

**Comment by nicodev-git** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nicodev-git** [comment]
Hey, @roryabraham  Please check my PR.

**Review by roryabraham — APPROVED** [review]
Looks great! Thanks!

**Comment by roryabraham** [comment]
@nicodev-git Sorry for the inconvenience, but this repo requires that all commits be signed. Can you retroactively sign this commit? I think this command _should_ work:

```
git commit --amend --signoff
git push
```

More information [here](git commit --amend --signoff)

**Comment by roryabraham** [comment]
Once your commit is signed, I can merge and deploy this change

**Comment by supertech-999** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nicodev-git** [comment]
Hi, @roryabraham   I see my commit was signed.  what else do I have to do?

**Comment by roryabraham** [comment]
Hey @nicodev-git, unfortunately I'm still unable to merge. I think you may have to sign the merge-commit (25a532e) as well.

**Comment by nicodev-git** [comment]
I commented on the all commits.  Please check it again.

**Comment by roryabraham** [comment]
Hmmm that didn't work. Can you try running this command on your branch:

```
git rebase --signoff HEAD~3
```

**Comment by nicodev-git** [comment]
done, and then?

**Comment by roryabraham** [comment]
Then push to your branch again

**Comment by nicodev-git** [comment]
image

**Comment by nicodev-git** [comment]
How about creating new PR from scratch?

**Comment by roryabraham** [comment]
You can do that or force-push your changes by adding the `-f` flag to your push

**Comment by roryabraham** [comment]
Looks like there is a merge conflict

**Comment by nicodev-git** [comment]
Fixed conflict and it seems Signature is verified.

**Review by roryabraham — APPROVED** [review]
LGTM 👍

**Review by nicodev-git — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by nicodev-git** [comment]
image
How can I sign in this commit?

**Comment by roryabraham** [comment]
It looks like only your latest merge commit is not signed, so try this:

```
git commit --amend --signoff
```

Then force-push your branch again

**Comment by roryabraham** [comment]
Also, so you don't have this issue in the future, follow [these steps](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/generating-a-new-gpg-key) to generate a gpg key, add it to your github account, and automatically sign all your commits

**Review by roryabraham — APPROVED** [review]
LGTM

**Comment by roryabraham** [comment]
Okay, I'm not sure why this isn't working. cc @rafecolton can you help us figure this out?

**Comment by rafecolton** [comment]
Given that the change is not huge, I think we can live with losing the history, so here is what I suggest:

1. Check out a new branch from your current branch
2. Rebase interactive and squash everything into a single commit
3. Ensure the one commit is signed
4. Open a new PR with the fixed branch
5. @roryabraham will confirm that the diffs are the same, merge the new PR, and close this one

**Comment by nicodev-git** [comment]
Is it correct to fork this repo and create PR?

**Comment by roryabraham** [comment]
> Is it correct to fork this repo and create PR? 

Yes, that's correct

**Pull request closed without merging**
