### PR TITLE
Added CODEOWNERS.md file

### PR DESCRIPTION
**Pull request by Luke9389**
### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/149443

### Tests 
Will be tested internally post-merge (this is a GH feature so we've gotta merge it to test it)

### CODE REVIEW

**Comment by Luke9389** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Luke9389** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Luke9389** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by tgolen — APPROVED** [review]

**Review by tgolen — COMMENTED** [review]
The lint warnings aren't your fault, so they don't necessarily need to be addressed in this PR, but it would be nice to clean up in a follow-up at some point (or maybe that would be a great contributor task).

**Pull request merged**
