### PR TITLE
Allow codefence regex to accept any characters after first three backticks

### PR DESCRIPTION
**Pull request by tsa321**
### Fixed Issues
$ https://github.com/Expensify/App/issues/45088

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
I have add unit tests for this issue.
1. What tests did you perform that validates your changed worked?
Update the related regex in the expensify-common in node module and send the test messages from composer of the App.
Test example:
````
```   
test
```
````

````
```  abc 
test
```
````

The code fence/ code block must be displayed properly.

Verify the displayed message is displayed correctly.

# QA
1. What does QA need to do to validate your changes?
Same as test above
1. What areas to they need to test for regressions?
Code fence related regression tests.

### CODE REVIEW

**Comment by akinwale** [comment]
> @akinwale Just to confirm when sending message for example:
> 
> ```
> ```aaa
> bbb
> ```
> ```
> 
> The displayed message is:
> 
> ```
> bbb
> ```
> 
> The `aaa` text is removed. When editing the message, the `aaa` text no longer appears. It looks like:
> 
> ```
> ```
> bbb
> ```
> ```
> 
> This is expected behavior right?

I don't think this is expected behaviour. The characters within the codefence should be included instead of being stripped out.

**Comment by akinwale** [comment]
> @akinwale so the expected result would be:
> 
> ```
> aaa
> bbb
> ```
> 
> Right?

Yes, this is correct.

**Comment by deetergp** [comment]
> The characters within the codefence should be included instead of being stripped out.

I will volley here and say that yes, this is the expected behavior for every Markdown variant I have ever come across. If you want your text to appear in your codefence, you need to make sure it's after the line containing the triple backticks. In some variants the area after the backticks is reserved for specifying what flavor of context highlighting you want for you code.

**Comment by deetergp** [comment]
Yeah, I think allowing anything after the three backticks is fine, but expected behavior should be that they are not rendered in the code block.

**Comment by deetergp** [comment]
@tsa321 Let's not block on that. Right now we don't really support any kind of context highlighting, so there's no real reason for text to be there anyway.

**Comment by akinwale** [comment]
> kindly bump for review @akinwale. Or maybe @AndrewGable Could you review this instead?

Reviewing this today.

**Review by akinwale — APPROVED** [review]
LGTM.

**Comment by akinwale** [comment]
@tsa321 Looks good, thanks. Will wait for internal review from @deetergp or @AndrewGable and then you can create the corresponding PR in the Expensify App repo.

**Review by AndrewGable — APPROVED** [review]

**Pull request merged**
