### PR TITLE
add a rule to ExpensiMark.rules to fix issue #1476 of Expensify.Cash …

### PR DESCRIPTION
**Pull request by minbaghdasaryan**
expensify-common project

@laurenreidexpensify, @marcaaron, @Gonals will you please review this?

[Explanation of the change or anything fishy that is going on]

### Fixed Issues
$ https://github.com/Expensify/Expensify.cash/issues/1476

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
I have changed `ExpensiMark` file only, so unit tests on this file cover this change.

2. What tests did you perform that validates your changed worked?
I have run tests on the `expensify-common` project and all the tests suits was successfully passed.

# QA
1. What does QA need to do to validate your changes?
QA can validate my PR by updating `expensify-common` library and sending the test message on the relative issue.

2. What areas to they need to test for regressions?

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by minbaghdasaryan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by Gonals — CHANGES_REQUESTED** [review]
While the solution may work, it will add a whole new rule just to make sure we don't grab the parenthesis as part of the url.
Since we already have [rules that handle links](https://github.com/Expensify/expensify-common/blob/f3729a4e475626a38f77d8a2b6db67b71e268625/lib/ExpensiMark.js#L86-L113), let's just modify the regex in there to handle parentheses correctly.

**Comment by minbaghdasaryan** [comment]
Hi @Gonals 
Thanks for reviewing my PR and thanks for your suggestion. I will follow your instructions and will send PR in short time.

**Comment by laurenreidexpensify** [comment]
New PR - https://github.com/Expensify/expensify-common/pull/339

**Pull request closed without merging**
