### PR TITLE
Fix autolink isn't recognized when put before img markdown

### PR DESCRIPTION
**Pull request by bernhardoj**
### Fixed Issues
$ https://github.com/Expensify/App/issues/46491

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
A unit test is updated

1. What tests did you perform that validates your changed worked?
- Send a text + attachment message
- Edit the message
- Add a link (e.g., google.com) above the image markdown
- Verify the link text is rendered as a link
- Save the edit
- Verify the link message is saved as a link

To be able to test the live markdown, update the regex in `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js`

<details>
<summary>Android: Native</summary>

https://github.com/user-attachments/assets/315b0362-bc70-4b1c-9cdc-a8be8c33bad9

</details>

<details>
<summary>Android: mWeb Chrome</summary>

https://github.com/user-attachments/assets/b8115082-75b4-44af-9452-8d824d000e88

</details>

<details>
<summary>iOS: Native</summary>

https://github.com/user-attachments/assets/8dfeb085-d229-464d-8223-163894a59e66

</details>

<details>
<summary>iOS: mWeb Safari</summary>

https://github.com/user-attachments/assets/f514c227-e69d-48f2-a8b8-8a258ac80199

</details>

<details>
<summary>MacOS: Chrome / Safari</summary>

https://github.com/user-attachments/assets/f7316b29-6fbc-4b3e-a6aa-f1ff980922a5

</details>

<details>
<summary>MacOS: Desktop</summary>

https://github.com/user-attachments/assets/de19ab98-0cbb-4326-95fe-a694ef14ee50

</details>

# QA
1. What does QA need to do to validate your changes?
Same as Tests
1. What areas to they need to test for regressions?
Same as Tests

### CODE REVIEW

**Comment by bernhardoj** [comment]
I'm not sure how can we test [this](https://github.com/Expensify/expensify-common/pull/661#discussion_r1530208382) visually, but if we convert 
```
![# fake-heading *bold* _italic_ ~strike~ `code`](https://example.com/image.png)
``` 
using the ExpensiMark, the result is 
```
<img src="https://example.com/image.png" alt="# fake-heading *bold* _italic_ ~strike~ &#x60;code&#x60;" />
```

**Comment by bernhardoj** [comment]
Looks like changing `node_modules/@expensify/react-native-live-markdown/lib/parser/react-native-live-markdown-parser.js` for native doesn't work anymore. We can test the live markdown later in the live markdown repo..

**Comment by danieldoglas** [comment]
adding @dangrous since he's the CME for this issue. also cc @getusha

**Comment by dangrous** [comment]
thanks @danieldoglas! @getusha do you want to go through the testing on this one? I'm still seeing the bug but I might have incorrectly linked the module, so I'll try again in a bit

**Comment by getusha** [comment]
It's working fine for me

https://github.com/user-attachments/assets/5ef7cf15-d5b8-46fa-a202-3759c2980ad5

I'll test it on native as well

**Review by dangrous — APPROVED** [review]
okay finally got this to work. Looks good to me! Can we also please double check that we're not reintroducing https://github.com/Expensify/expensify-common/pull/661#discussion_r1530208382 ? Thanks!

**Comment by bernhardoj** [comment]
@dangrous I commented about that [here](https://github.com/Expensify/expensify-common/pull/782#issuecomment-2291112793)

**Pull request merged**
