### PR TITLE
Fix copy icon on multi-level domain emails

### PR DESCRIPTION
**Pull request by luacmartins**
cc @chiragsalian 

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/167534

# Tests
1. Send a concierge message to yourself with a multi-level email domain, e.g. `applausetester+qaabecciv@applause.expensifail.com`
2. Open the chat and verify that the copy icon shows after the email.
Screen Shot 2021-07-07 at 11 04 32 AM

# QA
Tests above.

### CODE REVIEW

**Comment by luacmartins** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by HorusGoul — CHANGES_REQUESTED** [review]
Could you add the email that triggered the error to the unit tests so we can catch this if there's a regression in the future? 🙏 

https://github.com/Expensify/expensify-common/blob/74d0282b7816c9ac2b1e79c13996d8b117474a02/__tests__/ExpensiMark-test.js#L288-L316

**Comment by luacmartins** [comment]
Updated! Thanks for that @HorusGoul!

**Review by HorusGoul — APPROVED** [review]
LGTM!

**Pull request merged**
