### PR TITLE
Fix/14941 whitespace above block quotes is stripped away

### PR DESCRIPTION
**Pull request by tienifr**
### Fixed Issues
$ https://github.com/Expensify/App/issues/14941

# Tests
## For all platforms
1, Compose a message like this:
```
normal text

> quote text

normal text
```
2, Post the message
3, Edit the message you posted
4, Verify that there is a blank line (and an even amount of space) above and below the block quote. The same message you sent in step 1 is shown in the editor

## Additional test for IOS and Android (to ensure there is no regression bug created by the PR)
1, Compose a message like this:
```
normal text
> quote text
normal text
```
2, Post the message
3, Verify that there is no extra space displayed when used non-quoted and quoted than non-quoted text

# QA
## For all platforms
1, Compose a message like this:
```
normal text

> quote text

normal text
```
2, Post the message
3, Edit the message you posted
4, Verify that there is a blank line (and an even amount of space) above and below the block quote. The same message you sent in step 1 is shown in the editor

## Additional test for IOS and Android (to ensure there is no regression bug created by the PR)
1, Compose a message like this:
```
normal text
> quote text
normal text
```
2, Post the message
3, Verify that there is no extra space displayed when used non-quoted and quoted than non-quoted text

### Screenshots/Videos
<details>
<summary>Web</summary>

https://user-images.githubusercontent.com/113963320/220953771-3d7338a7-1708-438a-8ba6-0c0134caa35d.mp4

</details>

<details>
<summary>Mobile Web - Chrome</summary>

https://user-images.githubusercontent.com/113963320/220953809-d08526ba-467f-4e26-8dd7-114fd15ae32a.mp4

</details>

<details>
<summary>Mobile Web - Safari</summary>

https://user-images.githubusercontent.com/113963320/220953844-3f9d3e04-62de-47b8-abcd-d34c19bbcbc1.mp4

</details>

<details>
<summary>Desktop</summary>

https://user-images.githubusercontent.com/113963320/220953882-c82dd006-f925-4d3e-ae3e-6e1c4880d95d.mp4

</details>

<details>
<summary>iOS</summary>

https://user-images.githubusercontent.com/113963320/220953907-aff74a22-6f07-42aa-95d2-d2b84b07efa4.mp4

</details>

<details>
<summary>Android</summary>

https://user-images.githubusercontent.com/113963320/220953932-57c20672-0f13-4382-b6c2-b7630752cc60.mp4

</details>

### CODE REVIEW

**Comment by tienifr** [comment]
Hi @dangrous this PR is ready for review. Please help me check it. Thank you!

**Review by dangrous — APPROVED** [review]
Looks good and tests pass!

**Comment by dangrous** [comment]
This should be good, just [answering some questions](https://github.com/Expensify/App/issues/14941#issuecomment-1441916741) before merging

**Comment by tienifr** [comment]
@rushatgabhane Noted. I just added screenshot for all platforms please help to check. Thanks

**Pull request merged**
