### PR TITLE
Fixed characters support between [] for Hyperlinks

### PR DESCRIPTION
**Pull request by mananjadhav**
Can someone please review it?

- Updated the regex for handling characters between [] for hyperlinks

### Fixed Issues
$ Fixes: [Expensify/App#4229](https://github.com/Expensify/App/issues/4229)

# Tests
1. "Test markdown and url links with inconsistent starting and closing parens" covers testing of the given changes
1. Tested against incorrect pairs, symbols, and special characters handling

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

### CODE REVIEW

**Comment by mananjadhav** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by parasharrajat** [comment]
recheck

**Review by AndrewGable — APPROVED** [review]

**Comment by AndrewGable** [comment]
I'll let @stitesExpensify do the final review and merge!

**Review by stitesExpensify — APPROVED** [review]

**Comment by parasharrajat** [comment]
I think it is good to let QA know that we should try complex combinations for the markup. Just to make sure nothing is broken.

**Comment by AndrewGable** [comment]
Sounds great @parasharrajat - Let's do that on the https://github.com/Expensify/App PR since I am not sure they get a checklist for these changes.

**Comment by stitesExpensify** [comment]
Hmm it looks like the commits are not PGP signed, so we can't merge this. @mananjadhav we're going to need you to check out [step 8 here](https://github.com/Expensify/App/blob/main/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request) and then create a new PR with the same changes.

**Comment by mananjadhav** [comment]
Noted. Closing and raising another PR.

**Comment by mananjadhav** [comment]
#401 https://github.com/Expensify/expensify-common/pull/401 PR raised with signed commits.

**Pull request closed without merging**
