### PR TITLE
nested quote fix

### PR DESCRIPTION
**Pull request by andrey010**
I changed the rule of a quote regarding my proposal in Expensify/App issue

### Fixed Issues
$ GH_LINK https://github.com/Expensify/App/issues/38199

# Tests
I checked with nom run test and manual testing in Expensify App chat

# QA
Should validate steps from https://github.com/Expensify/App/issues/38199

### CODE REVIEW

**Comment by andrey010** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by andrey010** [comment]
@nkuoch Hello could you please check, this PR block Expensify App issue

**Review by nkuoch — DISMISSED** [review]

**Comment by nkuoch** [comment]
Please fix lint

**Comment by andrey010** [comment]
> Please fix lint

done

**Review by nkuoch — APPROVED** [review]

**Comment by nkuoch** [comment]
You need all your commits to be [signed](https://github.com/Expensify/App/blob/ebe6aeaaff68f552d9704997531a3b4a849b0b09/contributingGuides/CONTRIBUTING.md#begin-coding-your-solution-in-a-pull-request).
So, either redo your commits and force push on this branch or create a new PR.

**Comment by andrey010** [comment]
I added .gitgonfig regarding instructions from the contributing guide. will recheck

**Pull request merged**
