### PR TITLE
fix codeFence linebreak missing when convert to markdown

### PR DESCRIPTION
**Pull request by situchan**
@aimane-chnaif @deetergp 

### Fixed Issues
$ https://github.com/Expensify/App/issues/15302

# Tests
1. Send this markdown: ```\n\n# test\n\n``` as new message
````
```

# test

```
````
2. Verify that converted html is `<pre><br />#&#32;test<br /><br /></pre>`
3. Edit this message
4. Verity that converted markdown is ```\n\n# test\n\n``` which is same as original one in Step 1.
5. Add one more line break at the beginning - ```\n\n\n# test\n\n``` and update message
````
```


# test

```
````
6. Verify that converted html is `<pre><br /><br />#&#32;test<br /><br /></pre>`
7. Edit this message
8. Verity that converted markdown is ```\n\n\n# test\n\n``` which is same as original one in Step 5.

# QA
Same as Tests step

https://user-images.githubusercontent.com/108292595/225628295-6b7f5b5a-b1dd-4612-8d00-b4840f65084a.mov

### CODE REVIEW

**Comment by situchan** [comment]
_**I have read the CLA Document and I hereby sign the CLA**_

**Review by PauloGasparSv — APPROVED** [review]
I don't understand the regex change!

But I tested here and changes worked + our automated tests are passing so LGTM!

**Comment by situchan** [comment]
> I don't understand the regex change!
> 
> But I tested here and changes worked + our automated tests are passing so LGTM!

@PauloGasparSv hope you can get full understanding [here](https://github.com/Expensify/App/issues/15302#issuecomment-1463207060).

**Comment by situchan** [comment]
For safety, I pulled from latest `main`.
@deetergp bump for review

**Comment by deetergp** [comment]
@PauloGasparSv you should check out the GH, @situchan gave a very excellent explanation of the regex change 👍

**Review by deetergp — APPROVED** [review]
👍

**Pull request merged**
