### PR TITLE
Update to latest version of eslint-config-expensify

### PR DESCRIPTION
**Pull request by iwiznia**
TAG_REVIEWER will you please review this?

[Explanation of the change or anything fishy that is going on]

### Fixed Issues
https://github.com/Expensify/expensify-common/pull/407#issuecomment-902009232

# Tests
See https://github.com/Expensify/Web-Expensify/pull/31783

### CODE REVIEW

**Comment by iwiznia** [comment]
After merging this, you can unhold https://github.com/Expensify/Web-Expensify/pull/31783

**Comment by tgolen** [comment]
Were you able to test that this doesn't break iframes and tooltips? Do you want to add that to the PR tests?

**Review by tgolen — APPROVED** [review]

**Comment by iwiznia** [comment]
Oh, sorry, check the tests in the web-e PR and let me know if they are enough or I missed something.

**Comment by iwiznia** [comment]
> and tooltips? 

Wait, tooltips? I don't think I touched that here...

**Comment by tgolen** [comment]
Oh, sorry. I meant combobox, not tooltip. I'll see if I can find the web-e PR

**Comment by iwiznia** [comment]
It's here https://github.com/Expensify/Web-Expensify/pull/31783 I linked it in my comment above

**Comment by tgolen** [comment]
ah, haha, I'm just going everywhere this morning. Yeah, that looks good. Thanks!

**Pull request merged**
