### PR TITLE
Delete sms domain when having a v2 mention 

### PR DESCRIPTION
**Pull request by SzymczakJ**
### Fixed Issues
$ GH_LINK https://github.com/Expensify/App/issues/40969

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

### CODE REVIEW

**Comment by SzymczakJ** [comment]
@fnwbr 🙏

**Comment by fnwbr** [comment]
😘

**Comment by SzymczakJ** [comment]
damn I mentioned wrong person 😆, sorry for this blooper.

**Comment by SzymczakJ** [comment]
@flodnv can you give me review? it's really small 😄

**Review by flodnv — APPROVED** [review]

**Comment by flodnv** [comment]
😂 👍

**Pull request merged**
